var CURRENT_PERMISSION = '';
var PERMISSION_NOT_ADDED_MSG = '';
var CONSOLE_STYLE = 'color: orange; font-weight: bold;';
(function() {
    var _old_alert = window.alert;
    window.alert = function() {
        // run some code when the alert pops up
        console.log(PERMISSION_NOT_ADDED_MSG, CONSOLE_STYLE);
        _old_alert.apply(window, arguments);
    };
})();

function setRoleFields() {
    // Set Header Fields
    nlapiSetFieldValue('rolename', 'Integration Developer');
    nlapiSetFieldValue('name', 'Integration Developer');
    nlapiSetFieldValue('centertype', 'BASIC');
    nlapiSetFieldValue('tfarequired', 'OFF');
    nlapiSetFieldValue('scriptid', '_sdfrole');


    // Set Permissions > Setup
    var setupPermissions = {
        "ADMI_MANAGE_OAUTH_TOKENS": 4,
        "ADMI_ACCOUNTINGLIST": 4,
        "ADMI_ACCOUNTING": 4,
        "ADMI_ACCTSETUP": 4,
        "ADMI_ADVANCED_TEMPLATES": 4,
        "ADMI_ALLOW_JS_HTML_UPLOAD": 4,
        "ADMI_ALLOWNONGLCHANGES": 4,
        "ADMI_ANALYTICS": 4,
        "ADMI_APPPUBLISHER": 4,
        "ADMI_NUMBERING": 4,
        "ADMI_BACKUPEXPORT": 4,
        "ADMI_BANK_CONNECTIVITY_CONFIG": 4,
        "ADMI_BILLINGINFO": 4,
        "ADMI_MANAGEROLES": 4,
        "ADMI_CRMLIST": 4,
        "ADMI_CASEALERT": 4,
        "ADMI_COMMERCECATEGORY": 4,
        "ADMI_COMPANY": 4,
        "ADMI_WEBSERVICESOVERRIDESSTRIG": 4,
        "ADMI_IMPORTOVERRIDESSTRIG": 4,
        "ADMI_CONVERTCLASSES": 4,
        "ADMI_CLASSESTOLOCS": 4,
        "ADMI_COPYPROJECTTASK": 4,
        "ADMI_HTMLFORMULA": 4,
        "ADMI_CREDITCARD": 4,
        "ADMI_CUSTADDRESSFORM": 4,
        "ADMI_CUSTBODYFIELD": 4,
        "ADMI_CUSTCATEGORY": 4,
        "ADMI_CUSTTASKS": 4,
        "ADMI_CUSTSECTION": 4,
        "ADMI_CUSTCENTER": 4,
        "ADMI_CUSTCOLUMNFIELD": 4,
        "ADMI_CUSTENTITYFIELD": 4,
        "ADMI_CUSTENTRYFORM": 4,
        "ADMI_CUSTEVENTFIELD": 4,
        "ADMI_CUSTFIELD": 4,
        "ADMI_CUSTEMAILLAYOUT": 4,
        "ADMI_CUSTITEMFIELD": 4,
        "ADMI_CUSTITEMNUMBERFIELD": 4,
        "ADMI_CUSTLIST": 4,
        "ADMI_CUSTLAYOUT": 4,
        "ADMI_CUSTRECORD": 4,
        "ADMI_MANAGECUSTOMSEGMENTS": 4,
        "ADMI_SUBLIST": 4,
        "ADMI_CUSTOMSUBLIST": 4,
        "ADMI_CUSTFIELDTAB": 4,
        "ADMI_CUSTTRANFIELD": 4,
        "ADMI_CUSTFORM": 4,
        "ADMI_CUSTTRANSACTION": 4,
        "ADMI_ENTITYSTATUS": 4,
        "ADMI_CUSTOMIZEDFIELDLEVELHELP": 4,
        "ADMI_TYPE": 4,
        "ADMI_DELETEDRECORD": 4,
        "ADMI_DEVICE_ID": 4,
        "ADMI_DUPLICATESETUP": 4,
        "ADMI_ENABLEFEATURES": 4,
        "ADMI_ESCALATIONTERRITORY": 4,
        "ADMI_ESCALATIONRULE": 4,
        "ADMI_EXPORTIIF": 4,
        "ADMI_FINCHARGEPREF": 4,
        "ADMI_REPOLAYOUTS": 4,
        "ADMI_REPOGROUPS": 4,
        "ADMI_IMPORTCSVFILE": 4,
        "ADMI_STATETAXIMPORT": 4,
        "ADMI_INTEGRAPP": 4,
        "ADMI_ISSUESETUP": 4,
        "ADMI_KPIREPORT": 4,
        "ADMI_CONVERTLEAD": 4,
        "ADMI_CLOSEPERIOD": 4,
        "ADMI_LOGIN_OAUTH": 4,
        "ADMI_LOGIN_OAUTH2": 4,
        "ADMI_ACCTPERIODS": 4,
        "ADMI_MANAGEPERMISSIONS": 4,
        "ADMI_MANAGEUSERS": 4,
        "ADMI_ISSUESHOWSTOPPER": 4,
        "ADMI_MHLEVEL": 4,
        "ADMI_MHNODE": 4,
        "ADMI_MHVERSION": 4,
        "ADMI_MIGRATEREVARRNGANDPLAN": 4,
        "ADMI_MOBILE_ACCESS": 4,
        "ADMI_CASEFORM": 4,
        "ADMI_CUSTRECORDFORM": 4,
        "ADMI_CUSTOMERFORM": 4,
        "ADMI_CUSTOTHERFIELD": 4,
        "ADMI_EMPLOYEELIST": 4,
        "ADMI_PERIODOVERRIDE": 4,
        "ADMI_PERIODCLOSING": 4,
        "ADMI_PROJECTTEMPLATE": 4,
        "ADMI_SAVEDASHBOARD": 4,
        "ADMI_EMPLCATEGORY": 4,
        "ADMI_KNOWLEDGEBASE": 4,
        "ADMI_REVIEW_CUSTOM_GL_RUNS": 4,
        "ADMI_WEBSERVICES": 4,
        "ADMI_SFASETUP": 4,
        "ADMI_SALESTERRITORY": 4,
        "ADMI_CUSTOMERRULE": 4,
        "ADMI_CSVIMPORTPREF": 4,
        "ADMI_CAMPAIGNEMAIL": 4,
        "ADMI_SETUPCOMPANY": 4,
        "ADMI_DOMAINS": 4,
        "ADMI_SETUPIMAGERESIZE": 4,
        "ADMI_WEBSERVICESSETUP": 4,
        "ADMI_STORESETUP": 4,
        "ADMI_SETUPYEARSTATUS": 4,
        "ADMI_CAMPAIGNSETUP": 4,
        "ADMI_APP_DEPLOYMENT": 4,
        "ADMI_BUNDLER": 4,
        "ADMI_BUNDLERAUDITTRAIL": 4,
        "ADMI_CUSTOMSCRIPT": 4,
        "ADMI_SS_SCHEDULING": 4,
        "ADMI_CASEISSUE": 4,
        "ADMI_CASEORIGIN": 4,
        "ADMI_CASEPRIORITY": 4,
        "ADMI_CASESTATUS": 4,
        "ADMI_CASETERRITORY": 4,
        "ADMI_CASERULE": 4,
        "ADMI_CASETYPE": 4,
        "ADMI_SUPPORTSETUP": 4,
        "ADMI_SWAPPRICES": 4,
        "ADMI_TEAMSELLINGCONTRIBUTION": 4,
        "ADMI_TELEPHONY_SETUP": 4,
        "ADMI_TRANSITEMTXT": 4,
        "ADMI_TWOFACTORAUTHBASE": 4,
        "ADMI_UNCATSITEITEMS": 4,
        "ADMI_UPDATEPRICES": 4,
        "ADMI_UPSELLSETUP": 4,
        "ADMI_MANAGE_OWN_OAUTH_TOKENS": 4,
        "ADMI_USER": 4,
        "ADMI_VICARIOUS_EMAILS": 4,
        "ADMI_AUDITLOGIN": 4,
        "ADMI_WEBSERVICESLOG": 4,
        "ADMI_VIEW_GENERAL_TOKENS": 4,
        "ADMI_VIEW_PAYMENT_CARD_TOKENS": 4,
        "ADMI_SITEMANAGEMENT": 4,
        "ADMI_WORKFLOW": 4
    };

    Object.keys(setupPermissions).forEach(function(permissionKey) {
        var permLevel = setupPermissions[permissionKey];
        nlapiSelectNewLineItem('setupmach');
        nlapiSetCurrentLineItemValue('setupmach', 'permkey4', permissionKey, true, true);
        nlapiSetCurrentLineItemValue('setupmach', 'permlevel4', permLevel.toString(), true, true);
        nlapiCommitLineItem('setupmach');
    });

    // Set Permissions > Reports
    var reportPermissions = {
        "REPO_ACCOUNTDETAIL": 1,
        "REPO_AP": 1,
        "GRAP_AP": 1,
        "REPO_AR": 1,
        "GRAP_AR": 1,
        "REPO_UNBILLED": 1,
        "REPO_AMORTIZATION": 1,
        "REPO_BALANCESHEET": 1,
        "REPO_BUDGET": 1,
        "REPO_CASHFLOW": 1,
        "REPO_DEFERREDEXPENSE": 1,
        "GRAP_EXP": 1,
        "REPO_FINANCIALS": 1,
        "REPO_1099": 4,
        "REPO_GSTSUMMARY": 1,
        "REPO_GL": 1,
        "REPO_GRANT_ACCESS": 4,
        "GRAP_INC": 1,
        "REPO_PANDL": 1,
        "REPO_INTEGRATION": 1,
        "REPO_INVENTORY": 1,
        "REPO_ISSUE": 1,
        "REPO_SNAPSHOTLEAD": 1,
        "REPO_MARKETING": 1,
        "GRAP_NETWORTH": 1,
        "REPO_PSTSUMMARY": 1,
        "REPO_PURCHASEORDER": 1,
        "REPO_PURCHASES": 1,
        "REPO_QUOTA": 1,
        "REPO_RECONCILE": 1,
        "REPO_CUSTOMIZATION": 4,
        "REPO_SCHEDULE": 4,
        "REPO_RETURNAUTH": 1,
        "REPO_REVREC": 1,
        "REPO_SALES": 1,
        "REPO_SALES_PROMO": 1,
        "REPO_SFA": 1,
        "REPO_SALESORDER": 1,
        "REPO_BOOKINGS": 1,
        "REPO_NONPOSTING": 1,
        "REPO_ANALYTICS": 3,
        "REPO_SUPPORT": 1,
        "REPO_SNAPSHOTCASE": 1,
        "REPO_TAX": 1,
        "REPO_TRAN": 1,
        "REPO_TRIALBALANCE": 1,
        "REPO_WEBSITE": 1,
        "REPO_WEBSTORE": 1
    };

    Object.keys(reportPermissions).forEach(function (permissionKey) {
        var permLevel = reportPermissions[permissionKey];
        nlapiSelectNewLineItem('repomach');
        nlapiSetCurrentLineItemValue('repomach', 'permkey2', permissionKey, true, true);
        nlapiSetCurrentLineItemValue('repomach', 'permlevel2', permLevel.toString(), true, true);
        nlapiCommitLineItem('repomach');
    });


    // Set Permissions > Lists
    var listPermissions = {
        "LIST_TRANNUMBERAUDITLOG": 4,
        "LIST_ACCOUNT": 4,
        "REGT_ACCTPAY": 4,
        "REGT_ACCTREC": 4,
        "LIST_OTHER_ADDRESS": 4,
        "LIST_ALLOCSCHEDULE": 4,
        "LIST_AMORTIZATION": 4,
        "REGT_BANK": 4,
        "LIST_BILLINBOUNDSHIPMENT": 4,
        "LIST_BILLOFMATERIALSINQUIRY": 4,
        "LIST_BOM": 4,
        "LIST_BILLINGSCHEDULE": 4,
        "LIST_BIN": 4,
        "LIST_BULK_PROCESSING": 1,
        "LIST_CRMGROUP": 4,
        "LIST_CALENDAR": 4,
        "LIST_CAMPAIGNHISTORY": 4,
        "LIST_CASE": 4,
        "LIST_COLORTHEME": 4,
        "LIST_COMPANY": 4,
        "LIST_COMPETITOR": 4,
        "LIST_COMPONENTWHEREUSEDINQUIRY": 4,
        "LIST_CONTACTROLE": 4,
        "LIST_CONTACTSUBSIDIARYRELATION": 1,
        "LIST_CONTACT": 4,
        "REGT_COGS": 4,
        "REGT_CREDCARD": 4,
        "LIST_CURRENCY": 4,
        "LIST_GLLINESAUDITLOG": 4,
        "LIST_GLLINESAUDITLOGSEG": 4,
        "LIST_CUSTRECORDENTRY": 4,
        "LIST_CUSTPROFILE": 4,
        "LIST_CUSTJOB": 4,
        "REGT_DEFEREXPENSE": 4,
        "REGT_DEFERREVENUE": 4,
        "LIST_DEPARTMENT": 4,
        "LIST_FILECABINET": 4,
        "LIST_CASE_DUPLICATES": 4,
        "LIST_ENTITY_DUPLICATES": 4,
        "LIST_EMAILTEMPLATE": 4,
        "LIST_ENTITYSUBSIDIARYRELATION": 1,
        "REGT_EQUITY": 4,
        "LIST_EVENT": 4,
        "LIST_CATEGORY": 4,
        "REGT_EXPENSE": 4,
        "LIST_EXPORT": 2,
        "LIST_FAIRVALUEDIMENSION": 4,
        "LIST_FAIRVALUEFORMULA": 4,
        "LIST_FAIRVALUEPRICE": 4,
        "LIST_FAXMESSAGE": 4,
        "LIST_FAXTEMPLATE": 4,
        "LIST_FINHISTORY": 4,
        "REGT_FIXEDASSET": 4,
        "LIST_GENERAL_TOKEN": 4,
        "LIST_GENERICRESOURCE": 4,
        "LIST_GIFT_CERTIFICATE": 4,
        "LIST_IMPORTED_EMPLOYEE_EXPENSE": 1,
        "LIST_INBOUNDSHIPMENT": 4,
        "REGT_INCOME": 4,
        "LIST_INTEGRAPP": 4,
        "LIST_INTERNALPUBLISH": 4,
        "LIST_ISSUE": 4,
        "LIST_ITEMDEMANDPLAN": 4,
        "LIST_ITEMREVENUECATEGORY": 4,
        "LIST_ITEM_REVISION": 4,
        "LIST_ITEMSUPPLYPLAN": 4,
        "LIST_ITEMTEMPLATE": 4,
        "LIST_STOREITEMLISTLA": 4,
        "LIST_ITEM": 4,
        "LIST_KNOWLEDGEBASE": 4,
        "LIST_CONVERTLEAD": 4,
        "LIST_MAILMESSAGE": 4,
        "LIST_MAILTEMPLATE": 4,
        "LIST_LOCATION": 4,
        "REGT_LONGTERMLIAB": 4,
        "LIST_MAILMERGE": 4,
        "LIST_CAMPAIGN": 4,
        "LIST_CRMTEMPLATE": 4,
        "LIST_MASSUPDATES": 4,
        "LIST_MEDIAITEMFOLDER": 4,
        "LIST_MEMDOC": 4,
        "REGT_NONPOSTING": 4,
        "LIST_HISTORY": 4,
        "REGT_OTHASSET": 4,
        "REGT_OTHCURRASSET": 4,
        "REGT_OTHCURRLIAB": 4,
        "REGT_OTHEXPENSE": 4,
        "REGT_OTHINCOME": 4,
        "LIST_OTHERNAME": 4,
        "LIST_PDFMESSAGE": 4,
        "LIST_PDFTEMPLATE": 4,
        "LIST_PAYMENT_CARD": 4,
        "LIST_PAYMENT_CARD_TOKEN": 4,
        "LIST_PAYMENT_INSTRUMENTS": 4,
        "LIST_PAYMETH": 4,
        "LIST_FIND": 4,
        "LIST_BIG_SEARCH": 2,
        "LIST_PHASEDPROCESS": 4,
        "LIST_CALL": 4,
        "LIST_PLANNEDREVENUE": 4,
        "LIST_PRESCATEGORY": 4,
        "LIST_PROJECTTASK": 4,
        "LIST_PROJECTTEMPLATE": 4,
        "LIST_PROMOTIONCODE": 4,
        "LIST_PUBLIC_TEMPLATE_CATEGORY": 4,
        "LIST_INFOITEMFORM": 4,
        "LIST_RSSFEED": 4,
        "LIST_PUBLISHSEARCH": 4,
        "LIST_QUANTITYPRICINGSCHEDULE": 4,
        "LIST_RECORDCUSTFIELD": 4,
        "LIST_CLASS": 4,
        "LIST_RELATEDITEMS": 4,
        "LIST_RESOURCE": 4,
        "LIST_REVENUEELEMENT": 4,
        "LIST_REVRECFIELDMAPPING": 4,
        "LIST_REVENUEPLAN": 4,
        "LIST_REVENUERECOGNITIONRULE": 4,
        "LIST_REVRECSCHEDULE": 4,
        "LIST_SALESCAMPAIGN": 4,
        "LIST_SALESROLE": 4,
        "LIST_SCHEDULEMASSUPDATES": 4,
        "LIST_SENTEMAIL": 1,
        "LIST_SHIPITEM": 4,
        "LIST_SHORTCUT": 4,
        "REGT_STAT": 4,
        "LIST_STORECATEGORY": 4,
        "LIST_INFOCATEGORY": 4,
        "LIST_INFOITEM": 4,
        "LIST_STORETAB": 4,
        "LIST_SUBSIDIARY": 4,
        "LIST_SCSNAPSHOT": 4,
        "LIST_SYSTEMEMAILTEMPLATE": 4,
        "LIST_TASK": 4,
        "LIST_TAXITEM": 4,
        "LIST_TAXSCHEDULE": 4,
        "LIST_TEMPLATE_CATEGORY": 4,
        "LIST_CRMMESSAGE": 4,
        "REGT_UNBILLEDREC": 4,
        "LIST_UNDELIVEREDEMAIL": 1,
        "LIST_UNIT": 4,
        "LIST_UPSELL": 4,
        "LIST_UPSELLWIZARD": 4,
        "LIST_VENDOR": 4,
        "LIST_SITEEMAILTEMPLATE": 4,
        "LIST_WEBSITE": 4,
        "LIST_WORKCALENDAR": 4
    };

    Object.keys(listPermissions).forEach(function (permissionKey) {
        var permLevel = listPermissions[permissionKey];
        nlapiSelectNewLineItem('listsmach');
        nlapiSetCurrentLineItemValue('listsmach', 'permkey3', permissionKey, true, true);
        nlapiSetCurrentLineItemValue('listsmach', 'permlevel3', permLevel.toString(), true, true);
        nlapiCommitLineItem('listsmach');
    });


    // Set Permissions > Transactions
    var transactionPermissions = {
        "TRAN_PAYMENTAUDIT": 4,
        "TRAN_INVADJST": 4,
        "TRAN_INVWKSHT": 4,
        "TRAN_AUDIT": 4,
        "TRAN_AUTO_CASH": 4,
        "TRAN_PURCHORDBILL": 4,
        "TRAN_VENDBILL": 4,
        "TRAN_BUILD": 4,
        "TRAN_WORKORDBUILD": 4,
        "TRAN_CASHSALE": 4,
        "TRAN_CASHRFND": 4,
        "TRAN_CHECK": 4,
        "TRAN_COPY_BUDGET": 4,
        "TRAN_INVCOUNT": 4,
        "TRAN_ALLOCSCHEDULE": 4,
        "TRAN_CREATEINVCOUNT": 4,
        "TRAN_CARDCHRG": 4,
        "TRAN_CARDRFND": 4,
        "TRAN_CUSTCRED": 4,
        "TRAN_VENDAUTHCREDIT": 4,
        "TRAN_FXREVAL": 4,
        "TRAN_CUSTDEP": 4,
        "TRAN_CUSTPYMT": 4,
        "TRAN_CUSTRFND": 4,
        "TRAN_DEPOSIT": 4,
        "TRAN_DEPAPPL": 4,
        "TRAN_INVDISTR": 4,
        "TRAN_FORECAST": 4,
        "TRAN_MGRFORECAST": 4,
        "TRAN_EDITPROFILE": 4,
        "TRAN_OPENBAL": 4,
        "TRAN_VENDCRED": 4,
        "TRAN_QUOTA": 4,
        "TRAN_EXPREPT": 4,
        "TRAN_FINCHRG": 4,
        "TRAN_FIND": 4,
        "TRAN_SALESORDFULFILL": 4,
        "TRAN_PRICELIST": 4,
        "TRAN_STATEMENT": 4,
        "TRAN_IMPORTOLBFILE": 4,
        "TRAN_CUSTINVC": 4,
        "TRAN_CUSTINVCAPPRV": 4,
        "TRAN_SALESORDINVOICE": 4,
        "TRAN_ITEMSHIP": 4,
        "TRAN_ITEMRCPT": 4,
        "TRAN_JOURNALAPPRV": 4,
        "TRAN_JOURNAL": 4,
        "TRAN_WORKORDMARKFIRMED": 4,
        "TRAN_WORKORDMARKRELEASED": 4,
        "TRAN_MATCHING_RULES": 4,
        "TRAN_OPPRTNTY": 4,
        "TRAN_ESTIMATEDCOSTOVERRIDE": 4,
        "TRAN_CLEARHOLD": 4,
        "TRAN_OWNTRNSF": 4,
        "TRAN_VENDPYMT": 4,
        "TRAN_TAXPYMT": 4,
        "TRAN_TAXLIAB": 4,
        "TRAN_EDITBANKINGINFO": 4,
        "TRAN_TIMEPOST": 4,
        "TRAN_POSTVENDORBILLVARIANCE": 4,
        "TRAN_POSTPERIODS": 4,
        "TRAN_GST_REFUND": 4,
        "TRAN_PURCHORD": 4,
        "TRAN_ESTIMATE": 4,
        "TRAN_PURCHORDRECEIVE": 4,
        "TRAN_RTNAUTHRECEIVE": 4,
        "TRAN_RECONCILE": 4,
        "TRAN_RTNAUTHCREDIT": 4,
        "TRAN_RTNAUTHAPPRV": 4,
        "TRAN_RTNAUTH": 4,
        "TRAN_REVARRNG": 4,
        "TRAN_REVARRNGAPPRV": 4,
        "TRAN_SALESORD": 4,
        "TRAN_SALESORDAPPRV": 4,
        "TRAN_BUDGET": 4,
        "TRAN_CUSTCHRG": 4,
        "TRAN_TRANSFER": 4,
        "TRAN_INVTRNFR": 4,
        "TRAN_TRNFRORD": 4,
        "TRAN_TRNFRORDAPPRV": 4,
        "TRAN_UNBUILD": 4,
        "TRAN_VENDBILLAPPRV": 4,
        "TRAN_VENDPYMTAPPRV": 4,
        "TRAN_VENDAUTHAPPRV": 4,
        "TRAN_VENDAUTH": 4,
        "TRAN_VENDAUTHRETURN": 4,
        "TRAN_GATEWAYNOTIFICATION": 4,
        "TRAN_PAYMENTEVENT": 4,
        "TRAN_WORKORD": 4
    };

    Object.keys(transactionPermissions).forEach(function (permissionKey) {
        var permLevel = transactionPermissions[permissionKey];
        nlapiSelectNewLineItem('tranmach');
        nlapiSetCurrentLineItemValue('tranmach', 'permkey1', permissionKey, true, true);
        nlapiSetCurrentLineItemValue('tranmach', 'permlevel1', permLevel.toString(), true, true);
        nlapiCommitLineItem('tranmach');
    });

    CURRENT_PERMISSION = '';
    PERMISSION_NOT_ADDED_MSG = '';
    CONSOLE_STYLE = '';
    console.log('Finished adding permissions. Please verify');
    alert('Finished adding permissions. Please verify');
}

setRoleFields();